# Generated by Django 2.0.6 on 2018-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_numero',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='mascara',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
