# Generated by Django 2.0.6 on 2018-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181002_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
