# Generated by Django 2.0.6 on 2018-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181002_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='UDC',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
