# Generated by Django 2.0.6 on 2018-10-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181002_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
