# Generated by Django 2.0.6 on 2018-10-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuario_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('id_pre_disp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Dispositivo')),
                ('id_pre_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('id_pre_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Ip')),
                ('id_pre_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('id_pre_sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Sala')),
                ('id_pre_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Usuario')),
            ],
        ),
    ]
