# Generated by Django 2.0.6 on 2018-10-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_prestamodispositivo_prestamoip_prestamosala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamodispositivo',
            name='id_pre_disp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Elemento'),
        ),
    ]
